None strategy
splitio/android-client pull request #427
Opened 2022-10-19 15:40 UTC by gthea

# Android SDK

## What did you accomplish?

- Added `ProcessStrategy` interface. The `apply` method receives only one `Impression` since it's what makes the most sense in this SDK.
- Created the `NoneStrategy`.

2022-10-19 20:44 UTC, mmelograno requested changes

2022-10-19 20:44 UTC, mmelograno commented on src/main/java/io/split/android/client/service/impressions/strategy/NoneStrategy.java
> +        Long previousTime = mImpressionsObserver.testAndSet(impression);
observer is not required for None strategy you should only track counts and mtks

2022-10-21 17:18 UTC, mmelograno approved these changes

2022-10-21 17:44 UTC, sanzmauro approved these changes
🚀

2022-10-21 18:46 UTC, merged